# Generated by Django 3.2.25 on 2025-01-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20250116_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='read',
        ),
        migrations.AddField(
            model_name='contacts',
            name='new_message',
            field=models.BooleanField(default=True),
        ),
    ]
