# Generated by Django 3.2.25 on 2025-01-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contacts_send_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='new_message',
        ),
        migrations.AddField(
            model_name='contacts',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
