# Generated by Django 3.2.25 on 2025-01-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20250121_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
