# Generated by Django 3.2.25 on 2025-01-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20250123_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='send_to',
            field=models.CharField(default='default=timezone.now', max_length=240),
            preserve_default=False,
        ),
    ]
