# Generated by Django 3.2.25 on 2025-01-29 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contacts_send_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.CharField(max_length=240)),
                ('subject', models.CharField(blank=True, max_length=52, null=True)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contacts')),
            ],
        ),
    ]
