# Generated by Django 3.2.25 on 2025-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='replied',
            name='name',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
