# Generated by Django 5.1.5 on 2025-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_replied_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='has_reply',
            field=models.BooleanField(default=False),
        ),
    ]
