# Generated by Django 5.1.5 on 2025-02-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contacts_has_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replied',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='new_reply',
            field=models.BooleanField(default=False),
        ),
    ]
