# Generated by Django 5.1.7 on 2025-04-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0012_alter_replied_options_contacts_new_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="phone",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
